[package]
name = "rs-piano-midi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midly = { version = "0.5", default-features = false, features = ["std", "alloc"] }
